# Generated by Django 5.2.4 on 2025-07-31 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма ставки')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время ставки')),
            ],
            options={
                'verbose_name': 'Ставка',
                'verbose_name_plural': 'Ставки',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название лота')),
                ('description', models.TextField(verbose_name='Описание и доп. информация')),
                ('start_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стартовая цена')),
                ('current_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Текущая цена')),
                ('telegram_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на продавца в Telegram')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Геолокация товара')),
                ('start_time', models.DateTimeField(verbose_name='Время старта')),
                ('end_time', models.DateTimeField(verbose_name='Время окончания')),
                ('status', models.CharField(choices=[('pending', 'Ожидает одобрения'), ('active', 'Активный'), ('scheduled', 'Запланирован'), ('completed', 'Завершен'), ('sold', 'Продан'), ('unsold', 'Не продан'), ('deleted', 'Удален')], default='pending', max_length=20, verbose_name='Статус лота')),
                ('document_type', models.CharField(choices=[('jewelry', 'Ювелирный'), ('historical', 'Исторически ценный'), ('standard', 'Стандартный')], default='standard', max_length=20, verbose_name='Тип документа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Лот',
                'verbose_name_plural': 'Лоты',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='LotImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='lot_images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение лота',
                'verbose_name_plural': 'Изображения лотов',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('transaction_type', models.CharField(max_length=50, verbose_name='Тип транзакции')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время транзакции')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-timestamp'],
            },
        ),
    ]
